### ISSUE TITLE
Volume function doesnt work in VSX-824

### ISSUE THREAD

**Issue by anuragsodhi** [csdozier/device-pioneer-vsx#2]

**Comment by dscarty** [comment]
Nor on vsx-1021k
But on/off works

**Comment by csdozier** [comment]
I dont have a google home, so never tested that integration.  I assume there is just a needed modification to the device handler, Ill look into it.  Otherwise, can you get me the smartthings live log when you try to invoke that command?

**Comment by dscarty** [comment]
Here's my live logs for on/off in Smartthings, the only commands Smartthings sees.
I can post live log of Smartthings volume control using app. if you like:
d0e5b1f8-f789-4c5c-80bb-e6c579b9f723  9:56:23 AM: debug update, request: params: [appId:d0e5b1f8-f789-4c5c-80bb-e6c579b9f723, param1:vsxreceiver, param2:5ca7d9dc-77ce-485b-a9ac-f54949b6a572, param3:power, param4:off, action:[GET:executeSmartAppGet, POST:executeSmartAppPost, PUT:executeSmartAppPut, DELETE:executeSmartAppDelete, OPTIONS:executeSmartAppOptions], controller:smartAppApi, id:5ca7d9dc-77ce-485b-a9ac-f54949b6a572, command:power, state:off], devices: [5ca7d9dc-77ce-485b-a9ac-f54949b6a572]
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:23 AM: debug update state, request: attribute: status state: paused
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:23 AM: debug update state, request: attribute: switch state: off
d0e5b1f8-f789-4c5c-80bb-e6c579b9f723  9:56:16 AM: debug update, request: params: [appId:d0e5b1f8-f789-4c5c-80bb-e6c579b9f723, param1:vsxreceiver, param2:5ca7d9dc-77ce-485b-a9ac-f54949b6a572, param3:power, param4:on, action:[GET:executeSmartAppGet, POST:executeSmartAppPost, PUT:executeSmartAppPut, DELETE:executeSmartAppDelete, OPTIONS:executeSmartAppOptions], controller:smartAppApi, id:5ca7d9dc-77ce-485b-a9ac-f54949b6a572, command:power, state:on], devices: [5ca7d9dc-77ce-485b-a9ac-f54949b6a572]
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:16 AM: debug update state, request: attribute: switch state: on
97c0a121-da18-4984-9f81-b07e3d002027  9:56:14 AM: debug Outgoing: [requestId:9163152330468395638, payload:[commands:[[ids:[5ca7d9dc-77ce-485b-a9ac-f54949b6a572], status:PENDING]]]]
97c0a121-da18-4984-9f81-b07e3d002027  9:56:14 AM: debug Turn on Pioneer Receiver
97c0a121-da18-4984-9f81-b07e3d002027  9:56:14 AM: debug Turn Pioneer Receiver on
97c0a121-da18-4984-9f81-b07e3d002027  9:56:14 AM: debug handleExecute()
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug GET /pioneervsxcontrol/main/power/on&apiserverurl=https%3A%2F%2Fgraph.api.smartthings.com%3A443%2Fapi%2Fsmartapps%2Finstallations HTTP/1.1 
Accept: */* 
User-Agent: Linux UPnP/1.0 SmartThings 
HOST: C0A80108:1FA6 

5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug 999
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug convertIPtoHex:8102
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug convertIPtoHex:192.168.1.8
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug Request:'power/on'
5ca7d9dc-77ce-485b-a9ac-f54949b6a572  9:56:14 AM: debug turning on

**Comment by csdozier** [comment]
OK, I dont see any request to change the volume.

I think there is not any integration for the music player capability in
smarthings to google home. If you refer to
https://support.smartthings.com/hc/en-us/articles/214609826-Google-Assistant-SmartThings-FAQ#Certified
:

Which SmartThings devices work with the Google Assistant?

The Google Assistant can control light bulbs, plugs, on/off switches,
dimmers, and thermostats found on our Works with SmartThings page
<https://www.smartthings.com/works-with-smartthings>.
It doesnt list anything on the page about volume control I suppose I can
change the device type to support .. it might work if the device handler is
set with capability "switchlevel" as I already have the setlevel function,
but I have no way to test it.

**Comment by dscarty** [comment]
That the receiver swiches on/off with the python script is all that matters. Thanks for all your hard work.

**Comment by anuragsodhi** [comment]
after re-doing the whole process, volume button works.. Closing issue
